<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405183804 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id_categorie INT AUTO_INCREMENT NOT NULL, nom_categorie VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, couleur VARCHAR(7) DEFAULT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_497DD634DD8CA775 (nom_categorie), PRIMARY KEY (id_categorie)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE compte (id_compte INT AUTO_INCREMENT NOT NULL, numero_compte VARCHAR(50) NOT NULL, type_compte VARCHAR(50) NOT NULL, devise VARCHAR(10) NOT NULL, solde NUMERIC(15, 2) NOT NULL, solde_initial NUMERIC(15, 2) NOT NULL, taux_interet NUMERIC(5, 2) DEFAULT NULL, date_ouverture DATE NOT NULL, date_cloture DATE DEFAULT NULL, statut VARCHAR(50) NOT NULL, iban VARCHAR(50) DEFAULT NULL, bic VARCHAR(50) DEFAULT NULL, score_fiabilite INT DEFAULT NULL, score_usage INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, id_utilisateur BIGINT NOT NULL, UNIQUE INDEX UNIQ_CFF652609731415A (numero_compte), INDEX IDX_CFF6526050EAE44 (id_utilisateur), PRIMARY KEY (id_compte)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE credit (id_credit INT AUTO_INCREMENT NOT NULL, type_credit VARCHAR(50) NOT NULL, montant_demande NUMERIC(15, 2) NOT NULL, montant_approuve NUMERIC(15, 2) DEFAULT NULL, montant_restant NUMERIC(15, 2) DEFAULT NULL, taux_interet NUMERIC(5, 2) NOT NULL, duree_mois INT NOT NULL, date_demande DATE NOT NULL, date_approbation DATE DEFAULT NULL, date_remboursement_debut DATE DEFAULT NULL, date_remboursement_fin DATE DEFAULT NULL, statut VARCHAR(50) NOT NULL, raison_rejet LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, id_compte INT NOT NULL, id_utilisateur BIGINT NOT NULL, INDEX IDX_1CC16EFEE9C1E78D (id_compte), INDEX IDX_1CC16EFE50EAE44 (id_utilisateur), PRIMARY KEY (id_credit)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE document (id_document INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) NOT NULL, type_document VARCHAR(100) NOT NULL, chemin_fichier VARCHAR(500) NOT NULL, taille_fichier INT DEFAULT NULL, date_document DATE DEFAULT NULL, date_echeance DATE DEFAULT NULL, statut ENUM(\'valide\',\'expire\',\'a_renouveler\',\'archive\') NOT NULL DEFAULT \'valide\', description LONGTEXT DEFAULT NULL, tags VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, id_utilisateur BIGINT NOT NULL, id_categorie INT DEFAULT NULL, id_dossier INT DEFAULT NULL, INDEX IDX_D8698A7650EAE44 (id_utilisateur), INDEX IDX_D8698A76C9486A13 (id_categorie), INDEX IDX_D8698A76E3D54947 (id_dossier), PRIMARY KEY (id_document)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE dossier_document (id_dossier INT AUTO_INCREMENT NOT NULL, nom_dossier VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, id_utilisateur BIGINT NOT NULL, INDEX IDX_F029680150EAE44 (id_utilisateur), PRIMARY KEY (id_dossier)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE echeance (id_echeance INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) NOT NULL, date_echeance DATE NOT NULL, date_rappel DATE DEFAULT NULL, statut ENUM(\'pending\',\'notified\',\'completed\',\'overdue\') NOT NULL DEFAULT \'pending\', description LONGTEXT DEFAULT NULL, montant NUMERIC(15, 2) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, id_document INT NOT NULL, id_utilisateur BIGINT NOT NULL, INDEX IDX_40D9893B88B266E3 (id_document), INDEX IDX_40D9893B50EAE44 (id_utilisateur), PRIMARY KEY (id_echeance)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE compte ADD CONSTRAINT FK_CFF6526050EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFEE9C1E78D FOREIGN KEY (id_compte) REFERENCES compte (id_compte)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7650EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76C9486A13 FOREIGN KEY (id_categorie) REFERENCES categorie (id_categorie)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76E3D54947 FOREIGN KEY (id_dossier) REFERENCES dossier_document (id_dossier)');
        $this->addSql('ALTER TABLE dossier_document ADD CONSTRAINT FK_F029680150EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE echeance ADD CONSTRAINT FK_40D9893B88B266E3 FOREIGN KEY (id_document) REFERENCES document (id_document)');
        $this->addSql('ALTER TABLE echeance ADD CONSTRAINT FK_40D9893B50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE budget_limit DROP FOREIGN KEY `fk_budget_portefeuille`');
        $this->addSql('ALTER TABLE budget_limit DROP FOREIGN KEY `fk_budget_utilisateur`');
        $this->addSql('ALTER TABLE carte_virtuelle DROP FOREIGN KEY `fk_carte_portefeuille`');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY `depense_ibfk_1`');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY `facture_ibfk_1`');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY `facture_ibfk_2`');
        $this->addSql('ALTER TABLE portefeuille DROP FOREIGN KEY `fk_portefeuille_utilisateur`');
        $this->addSql('ALTER TABLE score_history DROP FOREIGN KEY `fk_score_history_utilisateur`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_transaction_dest`');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY `fk_transaction_source`');
        $this->addSql('ALTER TABLE user_discount DROP FOREIGN KEY `fk_discount_utilisateur`');
        $this->addSql('ALTER TABLE user_score DROP FOREIGN KEY `fk_score_utilisateur`');
        $this->addSql('ALTER TABLE virement_programme DROP FOREIGN KEY `fk_virement_carte_dest`');
        $this->addSql('ALTER TABLE virement_programme DROP FOREIGN KEY `fk_virement_carte_source`');
        $this->addSql('ALTER TABLE virement_programme DROP FOREIGN KEY `fk_virement_utilisateur`');
        $this->addSql('DROP TABLE budget');
        $this->addSql('DROP TABLE budget_limit');
        $this->addSql('DROP TABLE carte_virtuelle');
        $this->addSql('DROP TABLE categorie_depense');
        $this->addSql('DROP TABLE depense');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE portefeuille');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE score_history');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE user_discount');
        $this->addSql('DROP TABLE user_score');
        $this->addSql('DROP TABLE virement_programme');
        $this->addSql('DROP INDEX idx_utilisateur_role ON utilisateur');
        $this->addSql('ALTER TABLE utilisateur CHANGE role role ENUM(\'admin\',\'user\') NOT NULL DEFAULT \'user\', CHANGE solde solde NUMERIC(15, 2) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX uq_utilisateur_email TO UNIQ_1D1C63B3E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE budget (id_budget INT AUTO_INCREMENT NOT NULL, id_utilisateur INT NOT NULL, nom_budget VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, montant_total NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, montant_initial NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, periode VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'mensuel\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'mensuel, annuel, hebdomadaire\', statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'actif\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'actif, cloture, suspendu\', date_creation DATE NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_budget_statut (statut), INDEX idx_budget_periode (periode), INDEX idx_budget_utilisateur (id_utilisateur), PRIMARY KEY (id_budget)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE budget_limit (id BIGINT AUTO_INCREMENT NOT NULL, utilisateur_id BIGINT NOT NULL, portefeuille_id BIGINT DEFAULT NULL, periode_debut DATE NOT NULL, periode_fin DATE NOT NULL, type_periode ENUM(\'MENSUEL\', \'HEBDOMADAIRE\', \'QUOTIDIEN\') CHARACTER SET utf8mb4 DEFAULT \'\'\'MENSUEL\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, montant_limite NUMERIC(15, 2) NOT NULL, montant_utilise NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, UNIQUE INDEX uq_budget_utilisateur_periode (utilisateur_id, portefeuille_id, periode_debut, type_periode), INDEX idx_budget_periode (periode_debut, periode_fin), INDEX fk_budget_portefeuille (portefeuille_id), INDEX IDX_14877D96FB88E14F (utilisateur_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE carte_virtuelle (id BIGINT AUTO_INCREMENT NOT NULL, numero_carte VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, cvv VARCHAR(8) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, date_expiration DATE DEFAULT \'NULL\', solde NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, plafond NUMERIC(15, 2) DEFAULT \'1000.00\' NOT NULL, type ENUM(\'NORMAL\', \'GOLD\', \'SILVER\') CHARACTER SET utf8mb4 DEFAULT \'\'\'NORMAL\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, devise VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'\'\'TND\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, portefeuille_id BIGINT NOT NULL, is_active TINYINT DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_carte_type (type), UNIQUE INDEX uq_carte_numero (numero_carte), INDEX idx_carte_portefeuille (portefeuille_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE categorie_depense (id_categorie INT AUTO_INCREMENT NOT NULL, nom_categorie VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, icon VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, couleur VARCHAR(7) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, UNIQUE INDEX nom_categorie (nom_categorie), PRIMARY KEY (id_categorie)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE depense (id_depense INT AUTO_INCREMENT NOT NULL, id_utilisateur INT NOT NULL, id_budget INT DEFAULT NULL, categorie VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'Alimentation, Transport, Logement, Santé, Loisirs, etc.\', montant NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, date_depense DATE NOT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, mode_paiement VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'carte\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'carte, virement, cash, cheque\', created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_depense_categorie (categorie), INDEX idx_depense_date (date_depense), INDEX idx_depense_utilisateur (id_utilisateur), INDEX idx_depense_budget (id_budget), PRIMARY KEY (id_depense)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE facture (id_facture INT AUTO_INCREMENT NOT NULL, numero_facture VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, montant NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, date_facture DATE NOT NULL, date_echeance DATE NOT NULL, id_service INT DEFAULT NULL, id_produit INT DEFAULT NULL, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'en_attente\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'en_attente, payee, en_retard, annulee\', email_client VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, nom_client VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, adresse_client TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, telephone_client VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, date_envoi DATETIME DEFAULT \'NULL\', chemin_pdf VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, UNIQUE INDEX numero_facture (numero_facture), INDEX idx_facture_date (date_facture), INDEX id_service (id_service), INDEX idx_facture_echeance (date_echeance), INDEX id_produit (id_produit), INDEX idx_facture_numero (numero_facture), INDEX idx_facture_statut (statut), PRIMARY KEY (id_facture)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE portefeuille (id BIGINT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, solde_total NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, devise_principale VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'\'\'TND\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, utilisateur_id BIGINT NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_portefeuille_utilisateur (utilisateur_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE produit (id_produit INT AUTO_INCREMENT NOT NULL, nom_produit VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, type_produit VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, montant NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, code_unique VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'disponible\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'disponible, indisponible, epuise\', date_creation DATE NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_produit_code (code_unique), UNIQUE INDEX code_unique (code_unique), INDEX idx_produit_statut (statut), INDEX idx_produit_type (type_produit), PRIMARY KEY (id_produit)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE score_history (id BIGINT AUTO_INCREMENT NOT NULL, utilisateur_id BIGINT NOT NULL, score_ancien INT NOT NULL, score_nouveau INT NOT NULL, raison VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, date_calcul DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_score_history_user (utilisateur_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE service (id_service INT AUTO_INCREMENT NOT NULL, nom_service VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, type_service VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, tarif NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, frequence VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'mensuel, annuel, hebdomadaire, etc.\', date_debut DATE DEFAULT \'NULL\', date_fin DATE DEFAULT \'NULL\', statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'actif\'\'\' NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'actif, inactif, suspendu\', created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_service_statut (statut), INDEX idx_service_type (type_service), PRIMARY KEY (id_service)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE transaction (id BIGINT AUTO_INCREMENT NOT NULL, montant NUMERIC(15, 2) NOT NULL, devise VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'\'\'TND\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, date DATETIME DEFAULT \'current_timestamp()\' NOT NULL, type ENUM(\'DEPOT\', \'RETRAIT\', \'TRANSFERT\', \'VIREMENT_PROGRAMME\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, statut ENUM(\'SUCCESS\', \'FAILED\', \'PENDING\') CHARACTER SET utf8mb4 DEFAULT \'\'\'SUCCESS\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, carte_source_id BIGINT DEFAULT NULL, carte_dest_id BIGINT DEFAULT NULL, INDEX idx_transaction_type (type), INDEX idx_transaction_source (carte_source_id), INDEX idx_transaction_statut (statut), INDEX idx_transaction_dest (carte_dest_id), INDEX idx_transaction_date (date), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_discount (id BIGINT AUTO_INCREMENT NOT NULL, utilisateur_id BIGINT NOT NULL, pourcentage TINYINT DEFAULT 20 NOT NULL, code VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, utilisations_max INT DEFAULT 1 NOT NULL, utilisations INT DEFAULT 0 NOT NULL, date_expiration DATETIME DEFAULT \'NULL\', actif TINYINT DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_discount_user (utilisateur_id), INDEX idx_discount_code (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_score (id BIGINT AUTO_INCREMENT NOT NULL, utilisateur_id BIGINT NOT NULL, score INT DEFAULT 0 NOT NULL, budgets_respectes INT DEFAULT 0 NOT NULL, budgets_total INT DEFAULT 0 NOT NULL, transactions_regulieres INT DEFAULT 0 NOT NULL, dernier_calcul DATETIME DEFAULT \'current_timestamp()\' NOT NULL, UNIQUE INDEX uq_user_score (utilisateur_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE virement_programme (id BIGINT AUTO_INCREMENT NOT NULL, utilisateur_id BIGINT NOT NULL, carte_source_id BIGINT DEFAULT NULL, carte_dest_id BIGINT DEFAULT NULL, montant NUMERIC(15, 2) NOT NULL, devise VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'\'\'TND\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, destinataire VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, frequence ENUM(\'UNE_FOIS\', \'QUOTIDIEN\', \'HEBDOMADAIRE\', \'MENSUEL\') CHARACTER SET utf8mb4 DEFAULT \'\'\'UNE_FOIS\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, prochaine_execution DATETIME DEFAULT \'NULL\', statut ENUM(\'PENDING\', \'PROCESSING\', \'COMPLETED\', \'FAILED\', \'CANCELLED\') CHARACTER SET utf8mb4 DEFAULT \'\'\'PENDING\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, attempts INT DEFAULT 0 NOT NULL, actif TINYINT DEFAULT 1 NOT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, error_message TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, last_executed DATETIME DEFAULT \'NULL\', INDEX idx_virement_statut (statut), INDEX idx_virement_carte_source (carte_source_id), INDEX idx_virement_utilisateur (utilisateur_id), INDEX idx_virement_carte_dest (carte_dest_id), INDEX idx_virement_prochaine_exec (prochaine_execution), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE budget_limit ADD CONSTRAINT `fk_budget_portefeuille` FOREIGN KEY (portefeuille_id) REFERENCES portefeuille (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE budget_limit ADD CONSTRAINT `fk_budget_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE carte_virtuelle ADD CONSTRAINT `fk_carte_portefeuille` FOREIGN KEY (portefeuille_id) REFERENCES portefeuille (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE depense ADD CONSTRAINT `depense_ibfk_1` FOREIGN KEY (id_budget) REFERENCES budget (id_budget) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT `facture_ibfk_1` FOREIGN KEY (id_service) REFERENCES service (id_service) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT `facture_ibfk_2` FOREIGN KEY (id_produit) REFERENCES produit (id_produit) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE portefeuille ADD CONSTRAINT `fk_portefeuille_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE score_history ADD CONSTRAINT `fk_score_history_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_transaction_dest` FOREIGN KEY (carte_dest_id) REFERENCES carte_virtuelle (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT `fk_transaction_source` FOREIGN KEY (carte_source_id) REFERENCES carte_virtuelle (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_discount ADD CONSTRAINT `fk_discount_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_score ADD CONSTRAINT `fk_score_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE virement_programme ADD CONSTRAINT `fk_virement_carte_dest` FOREIGN KEY (carte_dest_id) REFERENCES carte_virtuelle (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE virement_programme ADD CONSTRAINT `fk_virement_carte_source` FOREIGN KEY (carte_source_id) REFERENCES carte_virtuelle (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE virement_programme ADD CONSTRAINT `fk_virement_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE compte DROP FOREIGN KEY FK_CFF6526050EAE44');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFEE9C1E78D');
        $this->addSql('ALTER TABLE credit DROP FOREIGN KEY FK_1CC16EFE50EAE44');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A7650EAE44');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76C9486A13');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76E3D54947');
        $this->addSql('ALTER TABLE dossier_document DROP FOREIGN KEY FK_F029680150EAE44');
        $this->addSql('ALTER TABLE echeance DROP FOREIGN KEY FK_40D9893B88B266E3');
        $this->addSql('ALTER TABLE echeance DROP FOREIGN KEY FK_40D9893B50EAE44');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE compte');
        $this->addSql('DROP TABLE credit');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE dossier_document');
        $this->addSql('DROP TABLE echeance');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE utilisateur CHANGE role role ENUM(\'admin\', \'user\') DEFAULT \'\'\'user\'\'\' NOT NULL, CHANGE solde solde NUMERIC(15, 2) DEFAULT \'0.00\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL');
        $this->addSql('CREATE INDEX idx_utilisateur_role ON utilisateur (role)');
        $this->addSql('ALTER TABLE utilisateur RENAME INDEX uniq_1d1c63b3e7927c74 TO uq_utilisateur_email');
    }
}
